name = "CarbonNowCLI"
uuid = "08bdf12a-7000-47b7-853d-1c82b5f9c15e"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.0.2"

[deps]
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
URIs = "1.5.1"
